Notify AbstractPlugin completed, always
Change AbstractPlugin to notify that it completed in a finally block, to
ensure the parent is notified always thus preventing it from "hanging"
after an uncaught exception (e.g. NoClassDefFoundError).

Related to #4038 - Source Code Disclosure (WEB-INF folder) fails with
Java 9