Catch more exceptions when invoking scripts
Change ExtensionScript to catch the exceptions NoClassDefFoundError and
ExceptionInInitializerError which might be thrown if a required class
being loaded throws an exception (which were not being reported in the
Script Console). Also, rename a method since it's now being used more
generically.