Correct SQL queries used in experimental DB
Change SqlTableContext to read the correct SQL queries when deleting all
context data (for a context and type).
Update name of the SQL query keys in the files hsqldb.properties and
mysqldb.properties.
Add missing primary keys in MySQL schema.

Fix #3703 - org.parosproxy.paros.db.DatabaseException:
java.sql.SQLException: Can not issue executeUpdate() or
executeLargeUpdate() for SELECTs